#ifndef MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_CONTROL_H_
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define JOINT__CONTROLLER_INTERFACE__VISIBILITY_EXPORT __attribute__((dllexport))
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_IMPORT __attribute__((dllimport))
#else
#define JOINT__CONTROLLER_INTERFACE__VISIBILITY_EXPORT __declspec(dllexport)
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_IMPORT __declspec(dllimport)
#endif
#ifdef MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_BUILDING_DLL
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_PUBLIC JOINT__CONTROLLER_INTERFACE__VISIBILITY_EXPORT
#else
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_PUBLIC MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_IMPORT
#endif
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_PUBLIC_TYPE MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_PUBLIC
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_LOCAL
#else
#define JOINT__CONTROLLER_INTERFACE__VISIBILITY_EXPORT __attribute__((visibility("default")))
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_IMPORT
#if __GNUC__ >= 4
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_PUBLIC __attribute__((visibility("default")))
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_LOCAL __attribute__((visibility("hidden")))
#else
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_PUBLIC
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_LOCAL
#endif
#define MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_PUBLIC_TYPE
#endif

#endif  // MOTEUS_CONTROLLER_INTERFACE__VISIBILITY_CONTROL_H_